import type { IconSet } from "./types";

// spanish words from spanish version of emojipedia.org
// if there are multiple words, i looked it up
const basicFoodIcons = [
  { filename: "1f347.png", spanishWords: ["las uvas"] },
  { filename: "1f349.png", spanishWords: ["la sandía"] },
  { filename: "1f34b.png", spanishWords: ["el limón"] },
  { filename: "1f34c.png", spanishWords: ["la banana", "el plátano"] },
  { filename: "1f34d.png", spanishWords: ["el ananá", "la piña"] },
  { filename: "1f96d.png", spanishWords: ["el mango"] },
  { filename: "1f34e.png", spanishWords: ["la manzana"] },
  { filename: "1f350.png", spanishWords: ["la pera"] },
  { filename: "1f351.png", spanishWords: ["el durazno", "el melocotón"] },
  { filename: "1f352.png", spanishWords: ["las cerezas"] },
  { filename: "1f353.png", spanishWords: ["la frutilla", "la fresa"] },
  { filename: "1f95d.png", spanishWords: ["el kiwi"] },
  { filename: "1f345.png", spanishWords: ["el tomate"] },
  { filename: "1f346.png", spanishWords: ["la berenjena"] },
  { filename: "1f954.png", spanishWords: ["la patata"] },
  { filename: "1f955.png", spanishWords: ["la zanahoria"] },
  // prettier-ignore
  { filename: "1fad1.png", spanishWords: ["el morrón verde", "el pimiento verde"] },
  { filename: "1f952.png", spanishWords: ["el pepino"] },
  { filename: "1f966.png", spanishWords: ["el brócoli", "el brécol"] },
  { filename: "1f9c4.png", spanishWords: ["el ajo"] },
  { filename: "1f9c5.png", spanishWords: ["la cebolla"] },
  { filename: "1f95c.png", spanishWords: ["el maní", "la cacahuete"] },
  { filename: "1fad8.png", spanishWords: ["los frijoles", "las alubias"] },
  { filename: "1f35e.png", spanishWords: ["el pan"] },
  { filename: "1f9c0.png", spanishWords: ["el queso"] },
  { filename: "1f357.png", spanishWords: ["el pollo"] },
  { filename: "1f969.png", spanishWords: ["la carne"] },
  { filename: "1f373.png", spanishWords: ["el huevo"] },
  { filename: "1f9c8.png", spanishWords: ["la manteca", "la mantequilla"] },
  { filename: "1f9c2.png", spanishWords: ["la sal"] },
  { filename: "1f364.png", spanishWords: ["el langostino", "el camarón"] },
  { filename: "1f35a.png", spanishWords: ["el arroz"] },
  { filename: "1f36a.png", spanishWords: ["la galleta"] },
];

const moreFoodIcons = [
  { filename: "1f348.png", spanishWords: ["el melón"] },
  { filename: "1f34a.png", spanishWords: ["la mandarina"] },
  { filename: "1fad0.png", spanishWords: ["los arándanos"] },
  { filename: "1fad2.png", spanishWords: ["las aceitunas", "las olivas"] },
  { filename: "1f965.png", spanishWords: ["el coco"] },
  { filename: "1f951.png", spanishWords: ["la palta", "el aguacate"] },
  // prettier-ignore
  { filename: "1f33d.png", spanishWords: ["el choclo", "el maíz", "el elote"] },
  { filename: "1f336.png", spanishWords: ["el ají", "el chile"] },
  { filename: "1f330.png", spanishWords: ["la castaña"] },
  { filename: "1f95e.png", spanishWords: ["los panqueques", "las tortitas"] },
  { filename: "1f953.png", spanishWords: ["la panceta", "el beicon"] },
  { filename: "1f354.png", spanishWords: ["la hamburguesa"] },
  { filename: "1f355.png", spanishWords: ["la pizza"] },
  { filename: "1f32d.png", spanishWords: ["el pancho", "el perro caliente"] },
  { filename: "1f96a.png", spanishWords: ["el sándwich"] },
  { filename: "1f32e.png", spanishWords: ["el taco"] },
  { filename: "1f32f.png", spanishWords: ["el burrito"] },
  { filename: "1fad4.png", spanishWords: ["el tamal"] },
  { filename: "1f958.png", spanishWords: ["la paella"] },
  { filename: "1f957.png", spanishWords: ["la ensalada"] },
  { filename: "1f37f.png", spanishWords: ["el pochoclo", "las palomitas"] },
  { filename: "1f35d.png", spanishWords: ["el espagueti"] },
  { filename: "1f366.png", spanishWords: ["el helado"] },
  { filename: "1f369.png", spanishWords: ["la dona"] },
  { filename: "1f370.png", spanishWords: ["la torta", "el pastel"] },
  { filename: "1f967.png", spanishWords: ["el pastel", "la tarta"] },
  { filename: "1f36b.png", spanishWords: ["el chocolate"] },
  { filename: "1f36c.png", spanishWords: ["el caramelo"] },
  { filename: "1f36e.png", spanishWords: ["el flan"] },
  { filename: "1f36f.png", spanishWords: ["la miel"] },
  { filename: "1f95b.png", spanishWords: ["la leche"] },
  { filename: "2615.png", spanishWords: ["el café"] },
  { filename: "1f375.png", spanishWords: ["el té verde"] },
  { filename: "1f377.png", spanishWords: ["el vino"] },
  { filename: "1f378.png", spanishWords: ["el cóctel"] },
  { filename: "1f37a.png", spanishWords: ["la cerveza"] },
  { filename: "1f943.png", spanishWords: ["el whisky"] },
  { filename: "1f9c3.png", spanishWords: ["el jugo", "el zumo"] },
  { filename: "1f9c9.png", spanishWords: ["el mate"] },
  { filename: "1f9ca.png", spanishWords: ["el hielo"] },
];

const beverageIcons = [
  { filename: "1f95b.png", spanishWords: ["la leche"] },
  { filename: "2615.png", spanishWords: ["el café"] },
  { filename: "1f375.png", spanishWords: ["el té verde"] },
  { filename: "1f377.png", spanishWords: ["el vino"] },
  { filename: "1f378.png", spanishWords: ["el cóctel"] },
  { filename: "1f37a.png", spanishWords: ["la cerveza"] },
  { filename: "1f943.png", spanishWords: ["el whisky"] },
  { filename: "1f9c3.png", spanishWords: ["el jugo", "el zumo"] },
  { filename: "1f9c9.png", spanishWords: ["el mate"] },
  { filename: "1f9ca.png", spanishWords: ["el hielo"] },
  { filename: "1f379.png", spanishWords: ["la bebida tropical"] },
];

const dessertIcons = [
  { filename: "1f366.png", spanishWords: ["el helado"] },
  { filename: "1f369.png", spanishWords: ["la dona"] },
  { filename: "1f36a.png", spanishWords: ["la galleta"] },
  { filename: "1f370.png", spanishWords: ["la torta", "el pastel"] },
  { filename: "1f967.png", spanishWords: ["el pastel", "la tarta"] },
  { filename: "1f36b.png", spanishWords: ["el chocolate"] },
  { filename: "1f36c.png", spanishWords: ["el caramelo"] },
  { filename: "1f36e.png", spanishWords: ["el flan"] },
];

const preparedFoodIcons = [
  { filename: "1f35e.png", spanishWords: ["el pan"] },
  { filename: "1f95e.png", spanishWords: ["los panqueques", "las tortitas"] },
  { filename: "1f354.png", spanishWords: ["la hamburguesa"] },
  { filename: "1f355.png", spanishWords: ["la pizza"] },
  { filename: "1f96a.png", spanishWords: ["el sándwich"] },
  { filename: "1f32e.png", spanishWords: ["el taco"] },
  { filename: "1f32f.png", spanishWords: ["el burrito"] },
  { filename: "1fad4.png", spanishWords: ["el tamal"] },
  { filename: "1f958.png", spanishWords: ["la paella"] },
  { filename: "1f957.png", spanishWords: ["la ensalada"] },
  { filename: "1f37f.png", spanishWords: ["el pochoclo", "las palomitas"] },
  { filename: "1f35d.png", spanishWords: ["el espagueti"] },
  { filename: "1f35a.png", spanishWords: ["el arroz"] },
];

const fruitIcons = [
  { filename: "1f347.png", spanishWords: ["las uvas"] },
  { filename: "1f348.png", spanishWords: ["el melón"] },
  { filename: "1f349.png", spanishWords: ["la sandía"] },
  { filename: "1f34a.png", spanishWords: ["la mandarina"] },
  { filename: "1f34b.png", spanishWords: ["el limón"] },
  { filename: "1f34c.png", spanishWords: ["la banana", "el plátano"] },
  { filename: "1f34d.png", spanishWords: ["el ananá", "la piña"] },
  { filename: "1f96d.png", spanishWords: ["el mango"] },
  { filename: "1f34e.png", spanishWords: ["la manzana"] },
  { filename: "1f350.png", spanishWords: ["la pera"] },
  { filename: "1f351.png", spanishWords: ["el durazno", "el melocotón"] },
  { filename: "1f352.png", spanishWords: ["las cerezas"] },
  { filename: "1f353.png", spanishWords: ["la frutilla", "la fresa"] },
  { filename: "1fad0.png", spanishWords: ["los arándanos"] },
  { filename: "1f95d.png", spanishWords: ["el kiwi"] },
  { filename: "1f965.png", spanishWords: ["el coco"] },
];

const vegetableIcons = [
  { filename: "1f951.png", spanishWords: ["la palta", "el aguacate"] },
  { filename: "1f346.png", spanishWords: ["la berenjena"] },
  { filename: "1f954.png", spanishWords: ["la patata"] },
  { filename: "1f955.png", spanishWords: ["la zanahoria"] },
  // prettier-ignore
  { filename: "1f33d.png", spanishWords: ["el choclo", "el maíz", "el elote"] },
  { filename: "1f336.png", spanishWords: ["el ají", "el chile"] },
  // prettier-ignore
  { filename: "1fad1.png", spanishWords: ["el morrón verde", "el pimiento verde"] },
  { filename: "1f952.png", spanishWords: ["el pepino"] },
  { filename: "1f966.png", spanishWords: ["el brócoli", "el brécol"] },
  { filename: "1f9c4.png", spanishWords: ["el ajo"] },
  { filename: "1f9c5.png", spanishWords: ["la cebolla"] },
  { filename: "1fad8.png", spanishWords: ["los frijoles", "las alubias"] },
  { filename: "1f345.png", spanishWords: ["el tomate"] },
  { filename: "1fad2.png", spanishWords: ["las aceitunas", "las olivas"] },
];

const basicAnimalIcons = [
  { filename: "1f400.png", spanishWords: ["la rata"] },
  { filename: "1f401.png", spanishWords: ["el ratón"] },
  { filename: "1f404.png", spanishWords: ["la vaca"] },
  { filename: "1f405.png", spanishWords: ["el tigre"] },
  { filename: "1f406.png", spanishWords: ["el leopardo"] },
  { filename: "1f407.png", spanishWords: ["el conejo"] },
  { filename: "1f408.png", spanishWords: ["el gato"] },
  { filename: "1f412.png", spanishWords: ["el mono"] },
  { filename: "1f415.png", spanishWords: ["el perro"] },
  { filename: "1f410.png", spanishWords: ["la cabra"] },
  { filename: "1f416.png", spanishWords: ["el cerdo"] },
  { filename: "1f418.png", spanishWords: ["el elefante"] },
  { filename: "1f419.png", spanishWords: ["el pulpo"] },
  { filename: "1f422.png", spanishWords: ["la tortuga"] },
  { filename: "1f427.png", spanishWords: ["el pingüino"] },
  { filename: "1f433.png", spanishWords: ["la ballena"] },
  { filename: "1f983.png", spanishWords: ["el pavo"] },
  { filename: "1f986.png", spanishWords: ["el pato"] },
  { filename: "1f982.png", spanishWords: ["el escorpión"] },
  { filename: "1f988.png", spanishWords: ["el tiburón"] },
  { filename: "1f989.png", spanishWords: ["el búho"] },
  { filename: "1f991.png", spanishWords: ["el calamar"] },
  { filename: "1f997.png", spanishWords: ["el grillo"] },
  { filename: "1f40a.png", spanishWords: ["el cocodrilo"] },
  { filename: "1f40d.png", spanishWords: ["la serpiente"] },
  { filename: "1f40e.png", spanishWords: ["el caballo"] },
  { filename: "1f41c.png", spanishWords: ["la hormiga"] },
  { filename: "1f41d.png", spanishWords: ["la abeja"] },
  { filename: "1f41e.png", spanishWords: ["la mariquita"] },
  { filename: "1f41f.png", spanishWords: ["el pez"] },
  { filename: "1f9a9.png", spanishWords: ["el flamenco"] },
  { filename: "1f9ad.png", spanishWords: ["la foca"] },
  { filename: "1fab0.png", spanishWords: ["la mosca"] },
  { filename: "1f577.png", spanishWords: ["la araña"] },
  { filename: "1fab1.png", spanishWords: ["el gusano"] },
  { filename: "1f98b.png", spanishWords: ["la mariposa"] },
  { filename: "1f98e.png", spanishWords: ["el lagarto"] },
  { filename: "1f99c.png", spanishWords: ["el loro"] },
  { filename: "1f99f.png", spanishWords: ["el mosquito"] },
];

const moreAnimalIcons = [
  { filename: "1f402.png", spanishWords: ["el buey"] },
  { filename: "1f403.png", spanishWords: ["el búfalo de agua"] },
  { filename: "1f409.png", spanishWords: ["el dragón"] },
  // probably should exclude since there are other birds
  // { filename: "1f426.png", spanishWords: ["el pájaro"] },
  { filename: "1f980.png", spanishWords: ["el cangrejo"] },
  { filename: "1f987.png", spanishWords: ["el murciélago"] },
  { filename: "1f990.png", spanishWords: ["el camarón"] },
  { filename: "1f992.png", spanishWords: ["la jirafa"] },
  { filename: "1f994.png", spanishWords: ["el erizo"] },
  { filename: "1f998.png", spanishWords: ["el canguro"] },
  { filename: "1f999.png", spanishWords: ["la llama"] },
  { filename: "1f40c.png", spanishWords: ["el caracol"] },
  { filename: "1f40f.png", spanishWords: ["el carnero"] },
  { filename: "1f43f.png", spanishWords: ["la ardilla listada"] },
  { filename: "1f9a1.png", spanishWords: ["el tejón"] },
  { filename: "1f9a2.png", spanishWords: ["el cisne"] },
  { filename: "1f9a5.png", spanishWords: ["el perezoso"] },
  { filename: "1f9a6.png", spanishWords: ["la nutria"] },
  // prettier-ignore
  { filename: "1f9a8.png", spanishWords: ["el zorrino", "la mofeta", "el zorrillo"] },
  { filename: "1f9ab.png", spanishWords: ["el castor"] },
  { filename: "1f9ac.png", spanishWords: ["el bisonte"] },
  { filename: "1fab3.png", spanishWords: ["la cucaracha"] },
  { filename: "1f99a.png", spanishWords: ["el pavo real"] },
  { filename: "1f99b.png", spanishWords: ["el hipopótamo"] },
  // { filename: "1f99e.png", spanishWords: ["el bogavante", "la langosta"] },
  { filename: "1fab8.png", spanishWords: ["el coral"] },
  { filename: "1faba.png", spanishWords: ["el nido"] },
  { filename: "1f985.png", spanishWords: ["el águila"] },
  { filename: "1f54a.png", spanishWords: ["la paloma"] },
];

const bodyPartIcons = [
  { filename: "270b.png", spanishWords: ["la mano"] },
  { filename: "1f9b6.png", spanishWords: ["el pie"] },
  { filename: "1f442.png", spanishWords: ["la oreja"] },
  { filename: "1f443.png", spanishWords: ["la nariz"] },
  { filename: "1f9e0.png", spanishWords: ["el cerebro"] },
  { filename: "1fac0.png", spanishWords: ["el corazón"] },
  { filename: "1fac1.png", spanishWords: ["los pulmones"] },
  { filename: "1f9b7.png", spanishWords: ["el diente"] },
  { filename: "1f9b4.png", spanishWords: ["el hueso"] },
  { filename: "1f441.png", spanishWords: ["el ojo"] },
  { filename: "1f445.png", spanishWords: ["la lengua"] },
  { filename: "1f444.png", spanishWords: ["la boca"] },
  { filename: "1f9b1.png", spanishWords: ["el pelo", "el cabello"] },
  { filename: "1f9b5.png", spanishWords: ["la pierna"] },
  { filename: "1f4aa.png", spanishWords: ["el brazo"] },
  { filename: "1f485.png", spanishWords: ["las uñas"] },
];

const fantasyIcons = [
  { filename: "1f9d9.png", spanishWords: ["el mago"] },
  { filename: "1f9da.png", spanishWords: ["el hada"] },
  { filename: "1f9db.png", spanishWords: ["el vampiro"] },
  // mermaid?
  { filename: "1f9dd.png", spanishWords: ["el elfo", "el duende"] },
  { filename: "1f9de.png", spanishWords: ["el genio"] },
  { filename: "1f9df.png", spanishWords: ["el zombie"] },
  { filename: "1f9cc.png", spanishWords: ["el trol"] },
  { filename: "1f52e.png", spanishWords: ["la bola de cristal"] },
  { filename: "1fa84.png", spanishWords: ["la varita mágica"] },
  { filename: "1f984.png", spanishWords: ["el unicornio"] },
  { filename: "1f409.png", spanishWords: ["el dragón"] },
  { filename: "1f9dc.png", spanishWords: ["una persona sirena"] },
  { filename: "2694.png", spanishWords: ["las espadas"] },
  { filename: "1f3f9.png", spanishWords: ["arco y flecha"] },
  { filename: "1f6e1.png", spanishWords: ["el escudo"] },
  { filename: "1f47d.png", spanishWords: ["el extraterrestre"] },
  { filename: "1f916.png", spanishWords: ["el robot"] },
  { filename: "1f6f8.png", spanishWords: ["el platillo volador"] },
];

const sportsIcons = [
  { filename: "1f3c3.png", spanishWords: ["correr"] },
  { filename: "1f57a.png", spanishWords: ["bailar"] },
  { filename: "1f9d7.png", spanishWords: ["escalar"] },
  { filename: "1f93a.png", spanishWords: ["la esgrima"] },
  { filename: "1f3c7.png", spanishWords: ["montar a caballo"] },
  { filename: "26f7.png", spanishWords: ["esquiar"] },
  { filename: "1f3c2.png", spanishWords: ["el snowboard"] },
  { filename: "1f3cc.png", spanishWords: ["jugar golf"] },
  { filename: "1f3c4.png", spanishWords: ["hacer surf"] },
  { filename: "1f6a3.png", spanishWords: ["remar"] },
  { filename: "1f3ca.png", spanishWords: ["nadar"] },
  { filename: "1f3cb.png", spanishWords: ["la halterofilia"] },
  { filename: "1f6b4.png", spanishWords: ["el ciclismo"] },
  { filename: "1f938.png", spanishWords: ["la gimnasia"] },
  { filename: "1f93c.png", spanishWords: ["luchar"] },
  { filename: "1f9d8.png", spanishWords: ["el yoga"] },
  { filename: "26bd.png", spanishWords: ["el balón de fútbol"] },
  { filename: "26be.png", spanishWords: ["el béisbol"] },
  { filename: "1f94e.png", spanishWords: ["el sóftbol"] },
  { filename: "1f3c0.png", spanishWords: ["el balón de baloncesto"] },
  { filename: "1f3d0.png", spanishWords: ["la pelota de voleibol"] },
  { filename: "1f3c8.png", spanishWords: ["el balón de fútbol americano"] },
  { filename: "1f3c9.png", spanishWords: ["el balón de rugby"] },
  { filename: "1f3be.png", spanishWords: ["la pelota de tenis"] },
  { filename: "1f94f.png", spanishWords: ["el frisbee"] },
  { filename: "1f3b3.png", spanishWords: ["los bolos"] },
  { filename: "1f3d2.png", spanishWords: ["el hockey"] },
  { filename: "1f3a3.png", spanishWords: ["la pesca"] },

  // games
  { filename: "1f3ae.png", spanishWords: ["el mando de videoconsola"] },
  { filename: "1f579.png", spanishWords: ["el joystick"] },
  { filename: "1f3b0.png", spanishWords: ["la máquina tragaperras"] },
  { filename: "1f3b2.png", spanishWords: ["el dado"] },
  { filename: "1f9e9.png", spanishWords: ["la pieza de puzle"] },
  { filename: "1fa85.png", spanishWords: ["la piñata"] },
];

const colorIcons = [
  { filename: "1f7e5.png", spanishWords: ["rojo"] },
  { filename: "1f7e7.png", spanishWords: ["naranja"] },
  { filename: "1f7e8.png", spanishWords: ["amarillo"] },
  { filename: "1f7e9.png", spanishWords: ["verde"] },
  { filename: "1f7e6.png", spanishWords: ["azul"] },
  { filename: "1f7ea.png", spanishWords: ["morado"] },
  { filename: "1f7eb.png", spanishWords: ["café"] },
  { filename: "2b1b.png", spanishWords: ["negro"] },
  { filename: "2b1c.png", spanishWords: ["blanco"] },
];

const plantIcons = [
  { filename: "1f33c.png", spanishWords: ["la flor"] },
  { filename: "1f339.png", spanishWords: ["la rosa"] },
  { filename: "1f33b.png", spanishWords: ["el girasol"] },
  { filename: "1fab4.png", spanishWords: ["la planta"] },
  { filename: "1f332.png", spanishWords: ["el árbol"] },
  { filename: "1f334.png", spanishWords: ["la palmera"] },
  { filename: "1f335.png", spanishWords: ["el cactus"] },
  { filename: "1f33f.png", spanishWords: ["la hierba"] },
  { filename: "2618.png", spanishWords: ["la trébol"] },
  { filename: "1f343.png", spanishWords: ["las hojas"] },
];

const musicIcons = [
  { filename: "1f508.png", spanishWords: ["el altavoz"] },
  { filename: "1f514.png", spanishWords: ["la campana"] },
  { filename: "1f3b5.png", spanishWords: ["la nota musical"] },
  { filename: "1f3a4.png", spanishWords: ["el micrófono"] },
  { filename: "1f3a7.png", spanishWords: ["los auriculares"] },
  { filename: "1f4fb.png", spanishWords: ["el radio"] },
  { filename: "1f3b7.png", spanishWords: ["el saxofón"] },
  { filename: "1f3ba.png", spanishWords: ["la trompeta"] },
  { filename: "1fa97.png", spanishWords: ["el acordeón"] },
  { filename: "1f3b9.png", spanishWords: ["el piano"] },
  { filename: "1f3bb.png", spanishWords: ["el violín"] },
  { filename: "1fa95.png", spanishWords: ["el banjo"] },
  { filename: "1f941.png", spanishWords: ["el tambor"] },
];

const schoolAndWorkIcons = [
  { filename: "1f4d6.png", spanishWords: ["el libro"] },
  { filename: "1f4d3.png", spanishWords: ["el cuaderno"] },
  { filename: "1f4c3.png", spanishWords: ["la página"] },
  { filename: "1f4f0.png", spanishWords: ["el periódico"] },
  { filename: "1f3f7.png", spanishWords: ["la etiqueta"] },
  { filename: "1fa99.png", spanishWords: ["la moneda"] },
  { filename: "1f4b7.png", spanishWords: ["el billete"] },
  { filename: "1f4b3.png", spanishWords: ["la tarjeta de crédito"] },
  { filename: "1f9fe.png", spanishWords: ["el ticket", "el recibo"] },
  { filename: "2709.png", spanishWords: ["el sobre"] },
  { filename: "1f4e7.png", spanishWords: ["el correo electrónico"] },
  { filename: "1f4e6.png", spanishWords: ["el paquete"] },
  { filename: "1f4eb.png", spanishWords: ["el buzón"] },
  { filename: "270f.png", spanishWords: ["el lápiz"] },
  { filename: "1f58a.png", spanishWords: ["el bolígrafo"] },
  { filename: "1f4bc.png", spanishWords: ["el maletín"] },
  { filename: "1f4c1.png", spanishWords: ["la carpeta"] },
  { filename: "1f4c5.png", spanishWords: ["el calendario"] },
  { filename: "1f4ca.png", spanishWords: ["el gráfico"] },
  { filename: "1f4cb.png", spanishWords: ["el portapapeles"] },
  { filename: "1f4ce.png", spanishWords: ["el clip"] },
  { filename: "1f4cf.png", spanishWords: ["la regla"] },
  { filename: "2702.png", spanishWords: ["las tijeras"] },
  { filename: "1f5c4.png", spanishWords: ["el archivador"] },
  { filename: "1f5d1.png", spanishWords: ["la papelera"] },
  { filename: "1f512.png", spanishWords: ["la cerradura"] },
  { filename: "1f511.png", spanishWords: ["la llave"] },
  { filename: "1f9d1-200d-1f393.png", spanishWords: ["estudiante"] },
  { filename: "1f9d1-200d-1f3eb.png", spanishWords: ["docente"] },
  { filename: "1f3eb.png", spanishWords: ["la escuela"] },
  { filename: "1f392.png", spanishWords: ["la mochila"] },
  { filename: "1f5a5.png", spanishWords: ["la computadora"] },
  { filename: "1f50c.png", spanishWords: ["el enchufe"] },
  { filename: "1f5a8.png", spanishWords: ["la impresora"] },
  { filename: "2328.png", spanishWords: ["el teclado"] },
  { filename: "1f5b1.png", spanishWords: ["el mouse"] },
  { filename: "1f4bf.png", spanishWords: ["el disco"] },
  { filename: "231a.png", spanishWords: ["el reloj"] },
  { filename: "23f1.png", spanishWords: ["el cronómetro"] },
  { filename: "23f2.png", spanishWords: ["el temporizador"] },
];

const spanishFlagIcons = [
  { filename: "1f1e8-1f1f4.png", spanishWords: ["Colombia"] },
  { filename: "1f1ea-1f1f8.png", spanishWords: ["España"] },
  { filename: "1f1fb-1f1ea.png", spanishWords: ["Venezuela"] },
  { filename: "1f1f5-1f1ea.png", spanishWords: ["Perú"] },
  { filename: "1f1ea-1f1e8.png", spanishWords: ["Ecuador"] },
  { filename: "1f1ec-1f1f9.png", spanishWords: ["Guatemala"] },
  { filename: "1f1e7-1f1f4.png", spanishWords: ["Bolivia"] },
  { filename: "1f1e8-1f1fa.png", spanishWords: ["Cuba"] },
  { filename: "1f1e9-1f1f4.png", spanishWords: ["Repúbica Dominicana"] },
  { filename: "1f1ed-1f1f3.png", spanishWords: ["Honduras"] },
  { filename: "1f1f5-1f1fe.png", spanishWords: ["Paraguay"] },
  { filename: "1f1f8-1f1fb.png", spanishWords: ["El Salvador"] },
  { filename: "1f1f3-1f1ee.png", spanishWords: ["Nicaragua"] },
  { filename: "1f1e8-1f1f7.png", spanishWords: ["Costa Rica"] },
  { filename: "1f1f5-1f1e6.png", spanishWords: ["Panamá"] },
  { filename: "1f1ec-1f1f6.png", spanishWords: ["Guinea Ecuatorial"] },
  { filename: "1f1f2-1f1fd.png", spanishWords: ["México"] },
  { filename: "1f1e6-1f1f7.png", spanishWords: ["Argentina"] },
  { filename: "1f1e8-1f1f1.png", spanishWords: ["Chile"] },
  { filename: "1f1fa-1f1fe.png", spanishWords: ["Uruguay"] },
  { filename: "1f1f5-1f1f7.png", spanishWords: ["Puerto Rico"] },
];

const vehicleIcons = [
  { filename: "1f697.png", spanishWords: ["el auto"] },
  { filename: "1f695.png", spanishWords: ["el taxi"] },
  { filename: "1f6fb.png", spanishWords: ["la camioneta"] },
  { filename: "1f68c.png", spanishWords: ["el colectivo", "el autobús"] },
  { filename: "1f691.png", spanishWords: ["la ambulancia"] },
  { filename: "1f692.png", spanishWords: ["el camión de bomberos"] },
  { filename: "1f69a.png", spanishWords: ["el camión"] },
  { filename: "1f69c.png", spanishWords: ["el tractor"] },
  { filename: "1f3cd.png", spanishWords: ["la moto"] },
  { filename: "1f6b2.png", spanishWords: ["la bicicleta"] },
  { filename: "1f687.png", spanishWords: ["el subte", "el metro"] },
  { filename: "2708.png", spanishWords: ["el avión"] },
  { filename: "1f681.png", spanishWords: ["el helicóptero"] },
  { filename: "1f6a2.png", spanishWords: ["el barco"] },
  { filename: "1f686.png", spanishWords: ["el tren"] },
  { filename: "1f3ce.png", spanishWords: ["el auto de carreras"] },
  { filename: "1f6f9.png", spanishWords: ["la patineta"] },
  { filename: "1f6fc.png", spanishWords: ["los patines"] },
  { filename: "1f680.png", spanishWords: ["el cohete"] },
  { filename: "26f5.png", spanishWords: ["el velero"] },
  { filename: "1f6f8.png", spanishWords: ["el platillo volador"] },
  { filename: "1fa82.png", spanishWords: ["el paracaídas"] },
];

const springAndFallIcons = [
  // spring:
  { filename: "1f338.png", spanishWords: ["la flor"] },
  { filename: "1f331.png", spanishWords: ["la planta joven"] },
  { filename: "1f41d.png", spanishWords: ["la abeja"] },
  { filename: "1f308.png", spanishWords: ["el arcoíris"] },
  { filename: "1f430.png", spanishWords: ["el conejo"] },
  { filename: "1f423.png", spanishWords: ["el pollito"] },
  { filename: "1f438.png", spanishWords: ["la rana"] },
  { filename: "1faba.png", spanishWords: ["el nido"] },
  // fall:
  { filename: "1f342.png", spanishWords: ["las hojas seca"] },
  { filename: "1f330.png", spanishWords: ["la castaña"] },
  { filename: "1f383.png", spanishWords: ["la calabaza"] },
  { filename: "2601.png", spanishWords: ["la nube"] },
  { filename: "1f32c.png", spanishWords: ["el viento"] },
  { filename: "1f43f.png", spanishWords: ["la ardilla listada"] },
  { filename: "1f967.png", spanishWords: ["la tarta"] },
  { filename: "2615.png", spanishWords: ["el café"] },
  { filename: "1fa81.png", spanishWords: ["el barrilete", "la cometa"] },
];

const summerIcons = [
  { filename: "2600.png", spanishWords: ["el sol"] },
  { filename: "1f3d6.png", spanishWords: ["la playa"] },
  { filename: "1f30a.png", spanishWords: ["la ola"] },
  { filename: "1f349.png", spanishWords: ["la sandía"] },
  { filename: "1f366.png", spanishWords: ["el helado"] },
  // prettier-ignore
  { filename: "1f576.png", spanishWords: ["los anteojos de sol", "las gafas de sol"] },
  { filename: "1f975.png", spanishWords: ["la cara con calor"] },
  { filename: "1f459.png", spanishWords: ["la bikini"] },
  { filename: "1f3c4.png", spanishWords: ["surfear"] },
  { filename: "1f3ca.png", spanishWords: ["nadar"] },
  { filename: "1f33b.png", spanishWords: ["el girasol"] },
  { filename: "1f379.png", spanishWords: ["la bebida tropical"] },
  { filename: "1fa74.png", spanishWords: ["las ojotas", "las chanclas"] },
];

const winterIcons = [
  { filename: "2744.png", spanishWords: ["el copo de nieve"] },
  { filename: "2603.png", spanishWords: ["el muñeco de nieve"] },
  { filename: "1f9e3.png", spanishWords: ["la bufanda"] },
  { filename: "1f9e4.png", spanishWords: ["los guantes"] },
  { filename: "1f976.png", spanishWords: ["la cara con frío"] },
  { filename: "1f525.png", spanishWords: ["el fuego"] },
  { filename: "26f7.png", spanishWords: ["esquiar"] },
  { filename: "1f3c2.png", spanishWords: ["el snowboard"] },
  { filename: "1f9ca.png", spanishWords: ["el hielo"] },
  { filename: "26f8.png", spanishWords: ["el patín de hielo"] },
  { filename: "1f6f7.png", spanishWords: ["el trineo"] },
  { filename: "1f9e5.png", spanishWords: ["el abrigo"] },
  { filename: "1f462.png", spanishWords: ["las botas"] },
];

const seasonsIcons = [
  { filename: "1f338.png", spanishWords: ["la flor"] },
  { filename: "1f331.png", spanishWords: ["la planta joven"] },
  { filename: "1f41d.png", spanishWords: ["la abeja"] },
  { filename: "1f308.png", spanishWords: ["el arcoíris"] },
  { filename: "2600.png", spanishWords: ["el sol"] },
  { filename: "1f3d6.png", spanishWords: ["la playa"] },
  { filename: "1f30a.png", spanishWords: ["la ola"] },
  { filename: "1f349.png", spanishWords: ["la sandía"] },
  { filename: "1f366.png", spanishWords: ["el helado"] },
  // prettier-ignore
  { filename: "1f576.png", spanishWords: ["los anteojos de sol", "las gafas de sol"] },
  { filename: "1f342.png", spanishWords: ["las hojas seca"] },
  { filename: "1f330.png", spanishWords: ["la castaña"] },
  { filename: "1f383.png", spanishWords: ["la calabaza"] },
  { filename: "2601.png", spanishWords: ["la nube"] },
  { filename: "1f32c.png", spanishWords: ["el viento"] },
  { filename: "2744.png", spanishWords: ["el copo de nieve"] },
  { filename: "2603.png", spanishWords: ["el muñeco de nieve"] },
  { filename: "1f9e3.png", spanishWords: ["la bufanda"] },
  { filename: "1f9e4.png", spanishWords: ["los guantes"] },
  { filename: "1f976.png", spanishWords: ["la cara con frío"] },
  { filename: "1f525.png", spanishWords: ["el fuego"] },
  { filename: "26f7.png", spanishWords: ["esquiar"] },
  { filename: "1f3c2.png", spanishWords: ["el snowboard"] },
  { filename: "1f9ca.png", spanishWords: ["el hielo"] },
  { filename: "26f8.png", spanishWords: ["el patín de hielo"] },
  { filename: "1f6f7.png", spanishWords: ["el trineo"] },
  { filename: "1f9e5.png", spanishWords: ["el abrigo"] },
  { filename: "1f462.png", spanishWords: ["las botas"] },
  { filename: "1f975.png", spanishWords: ["la cara con calor"] },
  { filename: "1f459.png", spanishWords: ["la bikini"] },
  { filename: "1f3c4.png", spanishWords: ["surfear"] },
  { filename: "1f3ca.png", spanishWords: ["nadar"] },
  { filename: "1f33b.png", spanishWords: ["el girasol"] },
  { filename: "1f379.png", spanishWords: ["la bebida tropical"] },
  { filename: "1f321.png", spanishWords: ["el termómetro"] },
  { filename: "1fa74.png", spanishWords: ["las ojotas", "las chanclas"] },
  { filename: "1f430.png", spanishWords: ["el conejo"] },
  { filename: "1f423.png", spanishWords: ["el pollito"] },
  { filename: "1f438.png", spanishWords: ["la rana"] },
  { filename: "1f43f.png", spanishWords: ["la ardilla listada"] },
  { filename: "1f967.png", spanishWords: ["la tarta"] },
  { filename: "2615.png", spanishWords: ["el café"] },
  { filename: "1fa81.png", spanishWords: ["el barrilete", "la cometa"] },
];

const clothingIcons = [
  // prettier-ignore
  { filename: "1f453.png", spanishWords: ["los anteojos", "los lentes", "las gafas"] },
  // prettier-ignore
  { filename: "1f576.png", spanishWords: ["los anteojos de sol", "las gafas de sol"] },
  { filename: "1f454.png", spanishWords: ["la corbata"] },
  { filename: "1f455.png", spanishWords: ["la camiseta"] },
  { filename: "1f456.png", spanishWords: ["los jeans"] },
  { filename: "1f9e3.png", spanishWords: ["la bufanda"] },
  { filename: "1f9e4.png", spanishWords: ["los guantes"] },
  { filename: "1f9e5.png", spanishWords: ["el abrigo"] },
  { filename: "1f9e6.png", spanishWords: ["las media", "los calcetines"] },
  { filename: "1f457.png", spanishWords: ["el vestido"] },
  { filename: "1fa71.png", spanishWords: ["la malla", "el traje de baño"] },
  { filename: "1fa72.png", spanishWords: ["la ropa interior"] },
  // prettier-ignore
  { filename: "1fa73.png", spanishWords: ["los shorts", "los pantalones cortos"] },
  { filename: "1f459.png", spanishWords: ["la bikini", "el bikini"] },
  { filename: "1f6cd.png", spanishWords: ["las bolsas de compras"] },
  { filename: "1f45c.png", spanishWords: ["el bolso"] },
  { filename: "1f392.png", spanishWords: ["la mochila"] },
  { filename: "1fa74.png", spanishWords: ["la chancla"] },
  { filename: "1f45e.png", spanishWords: ["el zapato"] },
  { filename: "1f45f.png", spanishWords: ["la zapatilla", "los tenis"] },
  { filename: "1f97e.png", spanishWords: ["la bota"] },
  { filename: "1f452.png", spanishWords: ["el sombrero"] },
  { filename: "1f48d.png", spanishWords: ["el anillo"] },
  { filename: "1f380.png", spanishWords: ["el lazo"] },
];

const weatherIcons = [
  { filename: "1f308.png", spanishWords: ["el arcoíris"] },
  { filename: "2600.png", spanishWords: ["el sol"] },
  { filename: "1f30a.png", spanishWords: ["la ola"] },
  // prettier-ignore
  { filename: "1f576.png", spanishWords: ["los anteojos de sol", "las gafas de sol"] },
  { filename: "2601.png", spanishWords: ["la nube"] },
  { filename: "1f32c.png", spanishWords: ["el viento"] },
  { filename: "1f328.png", spanishWords: ["la nieve"] },
  { filename: "2603.png", spanishWords: ["el muñeco de nieve"] },
  { filename: "1f32a.png", spanishWords: ["el tornado"] },
];

export const iconSets: IconSet[] = [
  // // how to use local icons instead of CDN: (make a "food-icons" dir within /public)
  // {
  //   name: "Food",
  //   iconDir: "/food-icons",
  //   icons: foodIcons,
  //   source: "Icon Humble Bundle",
  // },
  {
    name: "Basic Foods",
    iconDir: "https://twemoji.maxcdn.com/v/latest/72x72",
    icons: basicFoodIcons,
    source: "https://github.com/twitter/twemoji",
  },
  {
    name: "More Foods",
    iconDir: "https://twemoji.maxcdn.com/v/latest/72x72",
    icons: moreFoodIcons,
    source: "https://github.com/twitter/twemoji",
  },
  {
    name: "Fruits",
    iconDir: "https://twemoji.maxcdn.com/v/latest/72x72",
    icons: fruitIcons,
    source: "https://github.com/twitter/twemoji",
  },
  {
    name: "Vegetables",
    iconDir: "https://twemoji.maxcdn.com/v/latest/72x72",
    icons: vegetableIcons,
    source: "https://github.com/twitter/twemoji",
  },
  {
    name: "Prepared Foods",
    iconDir: "https://twemoji.maxcdn.com/v/latest/72x72",
    icons: preparedFoodIcons,
    source: "https://github.com/twitter/twemoji",
  },
  {
    name: "Beverages",
    iconDir: "https://twemoji.maxcdn.com/v/latest/72x72",
    icons: beverageIcons,
    source: "https://github.com/twitter/twemoji",
  },
  {
    name: "Desserts",
    iconDir: "https://twemoji.maxcdn.com/v/latest/72x72",
    icons: dessertIcons,
    source: "https://github.com/twitter/twemoji",
  },
  {
    name: "Basic Animals",
    iconDir: "https://twemoji.maxcdn.com/v/latest/72x72",
    icons: basicAnimalIcons,
    source: "https://github.com/twitter/twemoji",
  },
  {
    name: "More Animals",
    iconDir: "https://twemoji.maxcdn.com/v/latest/72x72",
    icons: moreAnimalIcons,
    source: "https://github.com/twitter/twemoji",
  },
  {
    name: "Body Parts",
    iconDir: "https://twemoji.maxcdn.com/v/latest/72x72",
    icons: bodyPartIcons,
    source: "https://github.com/twitter/twemoji",
  },
  {
    name: "Fantasy",
    iconDir: "https://twemoji.maxcdn.com/v/latest/72x72",
    icons: fantasyIcons,
    source: "https://github.com/twitter/twemoji",
  },
  {
    name: "Sports & Activities",
    iconDir: "https://twemoji.maxcdn.com/v/latest/72x72",
    icons: sportsIcons,
    source: "https://github.com/twitter/twemoji",
  },
  {
    name: "Colors",
    iconDir: "https://twemoji.maxcdn.com/v/latest/72x72",
    icons: colorIcons,
    source: "https://github.com/twitter/twemoji",
  },
  {
    name: "Plants",
    iconDir: "https://twemoji.maxcdn.com/v/latest/72x72",
    icons: plantIcons,
    source: "https://github.com/twitter/twemoji",
  },
  {
    name: "Music",
    iconDir: "https://twemoji.maxcdn.com/v/latest/72x72",
    icons: musicIcons,
    source: "https://github.com/twitter/twemoji",
  },
  {
    name: "School and Work",
    iconDir: "https://twemoji.maxcdn.com/v/latest/72x72",
    icons: schoolAndWorkIcons,
    source: "https://github.com/twitter/twemoji",
  },
  {
    name: "Vehicles",
    iconDir: "https://twemoji.maxcdn.com/v/latest/72x72",
    icons: vehicleIcons,
    source: "https://github.com/twitter/twemoji",
  },
  {
    name: "Seasons",
    iconDir: "https://twemoji.maxcdn.com/v/latest/72x72",
    icons: seasonsIcons,
    source: "https://github.com/twitter/twemoji",
  },
  {
    name: "Summer",
    iconDir: "https://twemoji.maxcdn.com/v/latest/72x72",
    icons: summerIcons,
    source: "https://github.com/twitter/twemoji",
  },
  {
    name: "Winter",
    iconDir: "https://twemoji.maxcdn.com/v/latest/72x72",
    icons: winterIcons,
    source: "https://github.com/twitter/twemoji",
  },
  {
    name: "Spring and Fall",
    iconDir: "https://twemoji.maxcdn.com/v/latest/72x72",
    icons: springAndFallIcons,
    source: "https://github.com/twitter/twemoji",
  },
  {
    name: "Weather",
    iconDir: "https://twemoji.maxcdn.com/v/latest/72x72",
    icons: weatherIcons,
    source: "https://github.com/twitter/twemoji",
  },
  {
    name: "Clothing",
    iconDir: "https://twemoji.maxcdn.com/v/latest/72x72",
    icons: clothingIcons,
    source: "https://github.com/twitter/twemoji",
  },
  {
    name: "Spanish-speaking Flags",
    iconDir: "https://twemoji.maxcdn.com/v/latest/72x72",
    icons: spanishFlagIcons,
    source: "https://github.com/twitter/twemoji",
  },
];
