import type { IconSet } from "./types";

export const foodIcons = [
  { filename: "apple.png", spanishWords: ["la manzana"] },
  { filename: "bananas.png", spanishWords: ["la banana", "el plátano"] },
  { filename: "beet.png", spanishWords: ["la remolacha", "el betabel"] },
  { filename: "bread.png", spanishWords: ["el pan"] },
  { filename: "broccoli.png", spanishWords: ["el brócoli", "el brécol"] },
  { filename: "cabbage_01.png", spanishWords: ["el repollo", "la col"] },
  { filename: "cake.png", spanishWords: ["la torta", "el pastel"] },
  { filename: "carrots_02.png", spanishWords: ["la zanahoria"] },
  { filename: "cheese_02.png", spanishWords: ["el queso"] },
  { filename: "cherries.png", spanishWords: ["las cerezas"] },
  { filename: "chicken.png", spanishWords: ["el pollo"] },
  { filename: "chocolate.png", spanishWords: ["el chocolate"] },
  { filename: "coconut.png", spanishWords: ["el coco"] },
  { filename: "coffee.png", spanishWords: ["el café"] },
  {
    filename: "corn_01.png",
    spanishWords: ["el choclo", "el maíz", "el elote"],
  },
  { filename: "cucumber.png", spanishWords: ["el pepino"] },
  { filename: "egg.png", spanishWords: ["el huevo"] },
  { filename: "eggplant_01.png", spanishWords: ["la berenjena"] },
  { filename: "fish_05.png", spanishWords: ["el pescado"] },
  { filename: "garlic.png", spanishWords: ["el ajo"] },
  { filename: "grapes.png", spanishWords: ["las uvas"] },
  { filename: "kiwi.png", spanishWords: ["el kiwi"] },
  { filename: "meat.png", spanishWords: ["la carne"] },
  { filename: "mushroom_06.png", spanishWords: ["el hongo", "el champiñón"] },
  { filename: "nuts.png", spanishWords: ["la nuez"] },
  { filename: "olive.png", spanishWords: ["la aceituna", "la oliva"] },
  { filename: "onion_01.png", spanishWords: ["la cebolla"] },
  { filename: "peach.png", spanishWords: ["el durazno", "el melocotón"] },
  {
    filename: "peas.png",
    spanishWords: ["las arvejas", "los guisantes", "los chícharos"],
  },
  {
    filename: "pepper_n.png",
    spanishWords: ["el morrón verde", "el pimiento verde"],
  },
  { filename: "pepper.png", spanishWords: ["el ají", "el chile"] },
  { filename: "pineapple_b.png", spanishWords: ["el ananá", "la piña"] },
  { filename: "pizza_f_06.png", spanishWords: ["la pizza"] },
  { filename: "plums.png", spanishWords: ["la ciruela"] },
  { filename: "pomegranate.png", spanishWords: ["la granada"] },
  { filename: "pumpkinf_03.png", spanishWords: ["el zapallo", "la calabaza"] },
  { filename: "radish.png", spanishWords: ["el rábano"] },
  { filename: "sandwich.png", spanishWords: ["el sándwich"] },
  { filename: "sausages.png", spanishWords: ["la salchicha"] },
  { filename: "shrimp.png", spanishWords: ["el langostino", "el camarón"] },
  { filename: "squash.png", spanishWords: ["el calabacín"] },
  { filename: "strawberry.png", spanishWords: ["la frutilla", "la fresa"] },
  { filename: "tomato.png", spanishWords: ["el tomate"] },
  { filename: "watermelon.png", spanishWords: ["la sandía"] },
  { filename: "wheat.png", spanishWords: ["el trigo"] },
];

export const iconSets: IconSet[] = [
  {
    name: "Food",
    iconDir: "food-icons",
    iconWidth: 256,
    iconHeight: 256,
    icons: foodIcons,
    source: "Icon Humble Bundle",
  },
];
