import type { IconSet } from "./types";

export const foodIcons = [
  { filename: "apple.png", spanishWords: ["la manzana"] },
  { filename: "bananas.png", spanishWords: ["la banana", "el plátano"] },
  { filename: "beet.png", spanishWords: ["la remolacha", "el betabel"] },
  { filename: "bread.png", spanishWords: ["el pan"] },
  { filename: "broccoli.png", spanishWords: ["el brócoli", "el brécol"] },
  { filename: "cabbage_01.png", spanishWords: ["el repollo", "la col"] },
  { filename: "cake.png", spanishWords: ["la torta", "el pastel"] },
  { filename: "carrots_02.png", spanishWords: ["la zanahoria"] },
  { filename: "cheese_02.png", spanishWords: ["el queso"] },
  { filename: "cherries.png", spanishWords: ["las cerezas"] },
  { filename: "chicken.png", spanishWords: ["el pollo"] },
  { filename: "chocolate.png", spanishWords: ["el chocolate"] },
  { filename: "coconut.png", spanishWords: ["el coco"] },
  { filename: "coffee.png", spanishWords: ["el café"] },
  {
    filename: "corn_01.png",
    spanishWords: ["el choclo", "el maíz", "el elote"],
  },
  { filename: "cucumber.png", spanishWords: ["el pepino"] },
  { filename: "egg.png", spanishWords: ["el huevo"] },
  { filename: "eggplant_01.png", spanishWords: ["la berenjena"] },
  { filename: "fish_05.png", spanishWords: ["el pescado"] },
  { filename: "garlic.png", spanishWords: ["el ajo"] },
  { filename: "grapes.png", spanishWords: ["las uvas"] },
  { filename: "kiwi.png", spanishWords: ["el kiwi"] },
  { filename: "meat.png", spanishWords: ["la carne"] },
  { filename: "mushroom_06.png", spanishWords: ["el hongo", "el champiñón"] },
  { filename: "nuts.png", spanishWords: ["la nuez"] },
  { filename: "olive.png", spanishWords: ["la aceituna", "la oliva"] },
  { filename: "onion_01.png", spanishWords: ["la cebolla"] },
  { filename: "peach.png", spanishWords: ["el durazno", "el melocotón"] },
  {
    filename: "peas.png",
    spanishWords: ["las arvejas", "los guisantes", "los chícharos"],
  },
  {
    filename: "pepper_n.png",
    spanishWords: ["el morrón verde", "el pimiento verde"],
  },
  { filename: "pepper.png", spanishWords: ["el ají", "el chile"] },
  { filename: "pineapple_b.png", spanishWords: ["el ananá", "la piña"] },
  { filename: "pizza_f_06.png", spanishWords: ["la pizza"] },
  { filename: "plums.png", spanishWords: ["la ciruela"] },
  { filename: "pomegranate.png", spanishWords: ["la granada"] },
  { filename: "pumpkinf_03.png", spanishWords: ["el zapallo", "la calabaza"] },
  { filename: "radish.png", spanishWords: ["el rábano"] },
  { filename: "sandwich.png", spanishWords: ["el sándwich"] },
  { filename: "sausages.png", spanishWords: ["la salchicha"] },
  { filename: "shrimp.png", spanishWords: ["el langostino", "el camarón"] },
  { filename: "squash.png", spanishWords: ["el calabacín"] },
  { filename: "strawberry.png", spanishWords: ["la frutilla", "la fresa"] },
  { filename: "tomato.png", spanishWords: ["el tomate"] },
  { filename: "watermelon.png", spanishWords: ["la sandía"] },
  { filename: "wheat.png", spanishWords: ["el trigo"] },
];

// spanish words from spanish version of emojipedia.org
// if there are multiple words, i looked it up
export const animalIcons = [
  { filename: "1f400.png", spanishWords: ["la rata"] },
  { filename: "1f401.png", spanishWords: ["el ratón"] },
  { filename: "1f402.png", spanishWords: ["el buey"] },
  { filename: "1f403.png", spanishWords: ["el búfalo de agua"] },
  { filename: "1f404.png", spanishWords: ["la vaca"] },
  { filename: "1f405.png", spanishWords: ["el tigre"] },
  { filename: "1f406.png", spanishWords: ["el leopardo"] },
  { filename: "1f407.png", spanishWords: ["el conejo"] },
  { filename: "1f408.png", spanishWords: ["el gato"] },
  { filename: "1f409.png", spanishWords: ["el dragón"] },
  { filename: "1f410.png", spanishWords: ["la cabra"] },
  { filename: "1f412.png", spanishWords: ["el mono"] },
  { filename: "1f415.png", spanishWords: ["el perro"] },
  { filename: "1f416.png", spanishWords: ["el cerdo"] },
  { filename: "1f418.png", spanishWords: ["el elefante"] },
  { filename: "1f419.png", spanishWords: ["el pulpo"] },
  { filename: "1f422.png", spanishWords: ["la tortuga"] },
  // probably should exclude since there are other birds
  // { filename: "1f426.png", spanishWords: ["el pájaro"] },
  { filename: "1f427.png", spanishWords: ["el pingüino"] },
  { filename: "1f433.png", spanishWords: ["la ballena"] },
  { filename: "1f980.png", spanishWords: ["el cangrejo"] },
  { filename: "1f982.png", spanishWords: ["el escorpión"] },
  { filename: "1f983.png", spanishWords: ["el pavo"] },
  { filename: "1f986.png", spanishWords: ["el pato"] },
  { filename: "1f987.png", spanishWords: ["el murciélago"] },
  { filename: "1f988.png", spanishWords: ["el tiburón"] },
  { filename: "1f989.png", spanishWords: ["el búho"] },
  { filename: "1f990.png", spanishWords: ["el camarón"] },
  { filename: "1f991.png", spanishWords: ["el calamar"] },
  { filename: "1f992.png", spanishWords: ["la jirafa"] },
  { filename: "1f994.png", spanishWords: ["el erizo"] },
  { filename: "1f997.png", spanishWords: ["el grillo"] },
  { filename: "1f998.png", spanishWords: ["el canguro"] },
  { filename: "1f999.png", spanishWords: ["la llama"] },
  { filename: "1f40a.png", spanishWords: ["el cocodrilo"] },
  { filename: "1f40c.png", spanishWords: ["el caracol"] },
  { filename: "1f40d.png", spanishWords: ["la serpiente"] },
  { filename: "1f40e.png", spanishWords: ["el caballo"] },
  { filename: "1f40f.png", spanishWords: ["el carnero"] },
  { filename: "1f41c.png", spanishWords: ["la hormiga"] },
  { filename: "1f41d.png", spanishWords: ["la abeja"] },
  { filename: "1f41e.png", spanishWords: ["la mariquita"] },
  { filename: "1f41f.png", spanishWords: ["el pez"] },
  { filename: "1f43f.png", spanishWords: ["la ardilla listada"] },
  { filename: "1f9a1.png", spanishWords: ["el tejón"] },
  { filename: "1f9a2.png", spanishWords: ["el cisne"] },
  { filename: "1f9a5.png", spanishWords: ["el perezoso"] },
  { filename: "1f9a6.png", spanishWords: ["la nutria"] },
  {
    filename: "1f9a8.png",
    spanishWords: ["el zorrino", "la mofeta", "el zorrillo"],
  },
  { filename: "1f9a9.png", spanishWords: ["el flamenco"] },
  { filename: "1f9ab.png", spanishWords: ["el castor"] },
  { filename: "1f9ac.png", spanishWords: ["el bisonte"] },
  { filename: "1f9ad.png", spanishWords: ["la foca"] },
  { filename: "1fab0.png", spanishWords: ["la mosca"] },
  { filename: "1fab1.png", spanishWords: ["el gusano"] },
  { filename: "1fab3.png", spanishWords: ["la cucaracha"] },
  { filename: "1f577.png", spanishWords: ["la araña"] },
  { filename: "1f98b.png", spanishWords: ["la mariposa"] },
  { filename: "1f98e.png", spanishWords: ["el lagarto"] },
  { filename: "1f99a.png", spanishWords: ["el pavo real"] },
  { filename: "1f99b.png", spanishWords: ["el hipopótamo"] },
  { filename: "1f99c.png", spanishWords: ["el loro"] },
  // { filename: "1f99e.png", spanishWords: ["el bogavante", "la langosta"] },
  { filename: "1f99f.png", spanishWords: ["el mosquito"] },
];

export const iconSets: IconSet[] = [
  {
    name: "Food",
    iconDir: "/food-icons",
    iconWidth: 256,
    iconHeight: 256,
    icons: foodIcons,
    source: "Icon Humble Bundle",
  },
  {
    name: "Animals",
    iconDir: "https://twemoji.maxcdn.com/v/latest/72x72",
    iconWidth: 72,
    iconHeight: 72,
    icons: animalIcons,
    source: "https://github.com/twitter/twemoji",
  },
];
