import { useEffect, useState } from "react";
import "./MemoriaGame.scss";
import { addDateToLocalStorage } from "../utils/localstorage";
import type { MemoriaPuzzle } from "./types";
import Win from "../components/Win";
import { GameString } from "../types";
import clsx from "clsx";
import EmojiTile from "../components/EmojiTile";

interface MemoriaGameProps {
  todayString: string;
  puzzle: MemoriaPuzzle;
  /** if false, the puzzle was generated by the user using the UI generator */
  isDailyPuzzle: boolean;
  /** is in colorblind mode if user has expressed a preference for that _and_ the puzzle needs it */
  isInColorblindMode: boolean;
  hasArgentinianBias: boolean;
}

export default function MemoriaGame(props: MemoriaGameProps) {
  const {
    hasArgentinianBias,
    isDailyPuzzle,
    isInColorblindMode,
    puzzle,
    todayString,
  } = props;

  const [hasWon, setHasWon] = useState(false);
  const [showWinScreen, setShowWinScreen] = useState(false);
  const [inProgressPuzzle, setInProgressPuzzle] = useState(puzzle);

  // @ts-ignore
  const win = () => {
    setHasWon(true);
    setShowWinScreen(true);

    if (isDailyPuzzle) {
      addDateToLocalStorage(GameString.ObjetoOculto, todayString);
    }
  };

  useEffect(() => {
    // onInit
    setInProgressPuzzle(puzzle);
    setHasWon(false);
    setShowWinScreen(false);
  }, [puzzle]);

  return (
    <div className={clsx("memoria-game", hasWon && "game-over")}>
      {showWinScreen && <Win canBeHidden={false} />}
      <div id="game">
        {inProgressPuzzle.slots.map((slot, i) => {
          if (!slot || !slot.emoji) {
            return <div key={`slot-${i}`} className="emoji-tile empty-tile" />;
          }
          return (
            <EmojiTile
              key={`slot-${i}`}
              icon={slot.emoji}
              iconDir={puzzle.iconDir}
              hasArgentinianBias={hasArgentinianBias}
              isImage={slot.isImage}
              isInColorblindMode={isInColorblindMode}
            />
          );
        })}
      </div>
    </div>
  );
}
