import { useEffect, useState } from "react";
import "./MemoriaGame.scss";
import "animate.css";
import { addDateToLocalStorage } from "../utils/localstorage";
import { type InProgressSlot, type MemoriaPuzzle } from "./types";
import Win from "../components/Win";
import { GameString } from "../types";
import clsx from "clsx";
import EmojiTile from "../components/EmojiTile";

interface MemoriaGameProps {
  todayString: string;
  puzzle: MemoriaPuzzle;
  /** if false, the puzzle was generated by the user using the UI generator */
  isDailyPuzzle: boolean;
  /** is in colorblind mode if user has expressed a preference for that _and_ the puzzle needs it */
  isInColorblindMode: boolean;
  isInGeneratorMode?: boolean;
  hasArgentinianBias: boolean;
}

export default function MemoriaGame(props: MemoriaGameProps) {
  const {
    hasArgentinianBias,
    isDailyPuzzle,
    isInColorblindMode,
    puzzle,
    todayString,
  } = props;

  const [hasWon, setHasWon] = useState(false);
  const [showWinScreen, setShowWinScreen] = useState(false);
  const [inProgressPuzzle, setInProgressPuzzle] = useState<InProgressSlot[]>(
    puzzle.slots,
  );
  const [attemptedMatch, setAttemptedMatch] = useState<number[]>([]);

  const win = () => {
    setHasWon(true);
    setShowWinScreen(true);

    if (isDailyPuzzle) {
      addDateToLocalStorage(GameString.Memoria, todayString);
    }
  };

  useEffect(() => {
    // onInit
    setInProgressPuzzle(puzzle.slots);

    setHasWon(false);
    setShowWinScreen(false);
  }, [puzzle]);

  // check for win condition
  useEffect(() => {
    if (!inProgressPuzzle.find((slot) => !slot.hasBeenMatched)) {
      win();
    }
  }, [inProgressPuzzle]);

  const checkForMatch = (cardA: InProgressSlot, cardB: InProgressSlot) => {
    return cardA.pairIndex === cardB.pairIndex;
  };

  const completeSuccessfulMatch = (pairIndex: number) => {
    setInProgressPuzzle((prevItems) => {
      return prevItems.map((slot) => {
        if (slot.pairIndex === pairIndex) {
          return { ...slot, hasBeenMatched: true };
        }
        return slot;
      });
    });
  };

  const onClick = (slotData: InProgressSlot) => {
    if (slotData.hasBeenMatched || attemptedMatch.includes(slotData.index))
      return;

    let nextMatchStatus = [...attemptedMatch];

    if (attemptedMatch.length > 1) {
      // clear tiles after failed match
      nextMatchStatus = [];
    }

    if (nextMatchStatus.length === 0) {
      setAttemptedMatch([slotData.index]);
    }

    if (nextMatchStatus.length === 1) {
      nextMatchStatus.push(slotData.index);
      const isMatch = checkForMatch(
        inProgressPuzzle[attemptedMatch[0]],
        slotData,
      );

      if (isMatch) {
        completeSuccessfulMatch(slotData.pairIndex);
        setAttemptedMatch([]);
      } else {
        // clear tiles after failed match
        setAttemptedMatch(nextMatchStatus);
      }
    }
  };

  const closeWinScreen = () => {
    setShowWinScreen(false);
  };

  return (
    <div className={clsx("memoria-game", hasWon && "game-over")}>
      {showWinScreen && <Win closeWinScreen={closeWinScreen} canBeHidden />}
      <div id="game">
        {inProgressPuzzle.map((slot, i) => {
          return (
            <EmojiTile
              key={`slot-${i}`}
              slotData={slot}
              onClick={onClick}
              isActive={attemptedMatch.includes(i)}
              iconDir={puzzle.iconDir}
              hasArgentinianBias={hasArgentinianBias}
              isInColorblindMode={isInColorblindMode}
            />
          );
        })}
      </div>
    </div>
  );
}
