import { useEffect, useRef, useState } from "react";
import "./OrtografiaMatchingGame.scss";
import "animate.css";
import { addDateToLocalStorage } from "../utils/localstorage";
import { GameString } from "../types";
import clsx from "clsx";
import type {
  OrtographiaPair,
  OrtografiaPuzzle,
  OrtographiaCardColor,
} from "./types";
import Srand from "seeded-rand";

interface OrtografiaMatchingGameProps {
  todayString: string;
  puzzle: OrtografiaPuzzle;
  /** if false, the puzzle was generated by the user using the UI generator */
  isDailyPuzzle: boolean;
  onWin: () => void;
}

const computedStyle = window.getComputedStyle(
  document.getElementById("root") || document.documentElement,
);
const COLORS = {
  blue200: computedStyle.getPropertyValue("--blue-200"),
  blue300: computedStyle.getPropertyValue("--blue-300"),
  green200: computedStyle.getPropertyValue("--green-200"),
  green300: computedStyle.getPropertyValue("--green-300"),
  orange200: computedStyle.getPropertyValue("--orange-200"),
  orange300: computedStyle.getPropertyValue("--orange-300"),
  purple200: computedStyle.getPropertyValue("--purple-200"),
  purple300: computedStyle.getPropertyValue("--purple-300"),
  yellow: computedStyle.getPropertyValue("--yellow"),
  yellowLight: computedStyle.getPropertyValue("--yellow-light"),
};
const CARD_COLORS: OrtographiaCardColor[] = [
  "purple",
  "yellow",
  "blue",
  "orange",
  "green",
];
const CARD_BORDERS = {
  blue: COLORS.blue300,
  green: COLORS.green300,
  orange: COLORS.orange300,
  purple: COLORS.purple300,
  yellow: COLORS.yellow,
};
const CARD_PATTERNS = {
  purple: `repeating-radial-gradient(circle,
    ${COLORS.purple200},
    ${COLORS.purple200} 10px,
    ${COLORS.purple300} 10px,
    ${COLORS.purple300} 20px
  )`,
  yellow: `repeating-linear-gradient(
    45deg,
    ${COLORS.yellow},
    ${COLORS.yellow} 10px,
    ${COLORS.yellowLight} 10px,
    ${COLORS.yellowLight} 20px
  )`,
  blue: `repeating-linear-gradient(
    -45deg,
    ${COLORS.blue200},
    ${COLORS.blue200} 10px,
    ${COLORS.blue300} 10px,
    ${COLORS.blue300} 20px
  )`,
  orange: `repeating-linear-gradient(
    to right,
    ${COLORS.orange300},
    ${COLORS.orange300} 10px,
    ${COLORS.orange200} 10px,
    ${COLORS.orange200} 20px
  )`,
  green: `repeating-linear-gradient(
    to bottom,
    ${COLORS.green200},
    ${COLORS.green200} 50%,
    ${COLORS.green300} 50%,
    ${COLORS.green300}
  )`,
};

export default function OrtografiaMatchingGame(
  props: OrtografiaMatchingGameProps,
) {
  const { isDailyPuzzle, onWin, puzzle, todayString } = props;

  const gameRef = useRef<HTMLDivElement>(null);
  const [hasWon, setHasWon] = useState(false);
  const [inProgressPuzzle, setInProgressPuzzle] = useState(puzzle);
  const [definitions, setDefinitions] = useState<string[]>([]);
  const [inProgressMatchSpanish, setInProgressMatchSpanish] =
    useState<string>();
  const [inProgressMatchEnglish, setInProgressMatchEnglish] =
    useState<string>();
  const [matchedPairs, setMatchedPairs] = useState<OrtographiaPair[]>([]);

  const getNextColor = () => {
    const usedColors = matchedPairs.map((pair) => pair.color);

    return (
      CARD_COLORS.find((color) => !usedColors.includes(color)) || CARD_COLORS[0]
    );
  };

  const win = () => {
    setHasWon(true);
    onWin();

    if (isDailyPuzzle) {
      addDateToLocalStorage(GameString.Ortografia, todayString);
    }
  };

  const shuffleDefinitions = () => {
    // use seeded shuffling so this date's puzzle is always in this order
    Srand.seed(Date.parse(todayString));
    const shuffled = Srand.sample(puzzle, inProgressPuzzle.length);
    const definitions = shuffled.map((word) => word.definition);
    setDefinitions(definitions);
  };

  useEffect(() => {
    // onInit
    shuffleDefinitions();

    setInProgressPuzzle(puzzle);

    setHasWon(false);
  }, [puzzle]);

  // check for win condition
  useEffect(() => {
    if (!inProgressPuzzle.find((word) => !word.isCorrect)) {
      win();
    } else if (matchedPairs.length === inProgressPuzzle.length) {
      // if all words are connected, drop incorrect connections
      // do it backwards so indices are correct
      for (let i = inProgressPuzzle.length - 1; i >= 0; i--) {
        const word = inProgressPuzzle[i];
        if (!word.isCorrect) {
          // remove from matchedPairs
          removePairFromArray(word.spanishWord);
        }
      }
    }
  }, [inProgressPuzzle, matchedPairs]);

  const addPairToArray = (spanish: string, english: string) => {
    setMatchedPairs((prevItems) => [
      ...prevItems,
      {
        spanish,
        english,
        color: getNextColor(),
      },
    ]);
    setInProgressMatchSpanish(undefined);
    setInProgressMatchEnglish(undefined);
    checkIfCorrectAndSet(spanish, english);
  };

  const removePairFromArray = (spanish?: string, english?: string) => {
    if (spanish) {
      setMatchedPairs((prevItems) =>
        prevItems.filter((item) => item.spanish !== spanish),
      );

      setCorrect(false, spanish);
    }
    if (english) {
      setMatchedPairs((prevItems) =>
        prevItems.filter((item) => item.english !== english),
      );

      setCorrect(false, undefined, english);
    }
  };

  const checkIfCorrectAndSet = (spanish: string, english: string) => {
    const word = inProgressPuzzle.find((w) => w.spanishWord === spanish);

    if (word?.definition === english) {
      setCorrect(true, spanish, english);
    }
  };

  const setCorrect = (
    isCorrect: boolean,
    spanish?: string,
    english?: string,
  ) => {
    setInProgressPuzzle((prevPuzzle) => {
      return prevPuzzle.map((word) => {
        if (spanish) {
          return word.spanishWord === spanish ? { ...word, isCorrect } : word;
        }
        if (english) {
          return word.definition === english ? { ...word, isCorrect } : word;
        }
        return word;
      });
    });
  };

  const onClickSpanish = (word: string) => {
    if (hasWon) return;

    // if the word clicked is already in `matchedPairs`, remove pair and start fresh
    const isPaired = matchedPairs.map((pair) => pair.spanish).includes(word);
    if (isPaired) {
      removePairFromArray(word);
    }

    // if the word clicked is the active one, make it unactive
    if (inProgressMatchSpanish === word) {
      setInProgressMatchSpanish(undefined);

      return;
    } else {
      setInProgressMatchSpanish(word);
    }

    if (inProgressMatchEnglish) {
      // add to array
      addPairToArray(word, inProgressMatchEnglish);
    }
  };

  const onClickEnglish = (word: string) => {
    if (hasWon) return;

    // if the word clicked is already in `matchedPairs`, remove pair and start fresh
    const isPaired = matchedPairs.map((pair) => pair.english).includes(word);
    if (isPaired) {
      removePairFromArray(undefined, word);
    }

    // if the word clicked is the active one, make it unactive
    if (inProgressMatchEnglish === word) {
      setInProgressMatchEnglish(undefined);
      return;
    } else {
      setInProgressMatchEnglish(word);
    }

    if (inProgressMatchSpanish) {
      // add to array
      addPairToArray(inProgressMatchSpanish, word);
    }
  };

  return (
    <div
      className={clsx("ortografia-matching-game", hasWon && "game-over")}
      ref={gameRef}
    >
      <div className="objective">Match the words to their definitions</div>
      <div id="game">
        <div className="spanish-column">
          {inProgressPuzzle.map((word) => {
            const pair = matchedPairs.find(
              (pair) => pair.spanish === word.spanishWord,
            );
            const isPaired = Boolean(pair);
            const isActive = inProgressMatchSpanish === word.spanishWord;

            return (
              <div
                onClick={() => onClickSpanish(word.spanishWord)}
                className={clsx(
                  "card animate__animated",
                  isActive && "active",
                  isPaired ? "animate__pulse paired" : "animate__headShake",
                  hasWon && "disabled",
                )}
                style={{
                  background: isActive
                    ? CARD_BORDERS[getNextColor()]
                    : isPaired
                      ? CARD_PATTERNS[pair!.color]
                      : "white",
                  borderColor: isPaired ? CARD_BORDERS[pair!.color] : "white",
                }}
                key={word.spanishWord}
              >
                <div className="inside">{word.spanishWord}</div>
              </div>
            );
          })}
        </div>
        <div className="english-column">
          {definitions.map((definition) => {
            const pair = matchedPairs.find(
              (pair) => pair.english === definition,
            );
            const isPaired = Boolean(pair);
            const isActive = inProgressMatchSpanish === definition;

            return (
              <div
                onClick={() => onClickEnglish(definition)}
                className={clsx(
                  "card animate__animated",
                  isActive && "active",
                  isPaired ? "animate__pulse paired" : "animate__headShake",
                  hasWon && "disabled",
                )}
                style={{
                  background: isActive
                    ? CARD_BORDERS[getNextColor()]
                    : isPaired
                      ? CARD_PATTERNS[pair!.color]
                      : "white",
                  borderColor: isPaired ? CARD_BORDERS[pair!.color] : "white",
                }}
                key={definition}
              >
                <div className="inside">{definition}</div>
              </div>
            );
          })}
        </div>
      </div>
    </div>
  );
}
