import { useEffect, useState } from "react";
import "./OrtografiaGame.scss";
import { delay } from "lodash";
import type { OrtografiaPuzzle } from "./types";

const DELAY_BETWEEN_LETTERS = 0; // ms

interface OrtografiaGameProps {
  todayString: string;
  puzzle: OrtografiaPuzzle;
  /** if false, the puzzle was generated by the user using the UI generator */
  isDailyPuzzle: boolean;
}

export default function OrtografiaGame(props: OrtografiaGameProps) {
  const { puzzle } = props;

  const [inProgressPuzzle, setInProgressPuzzle] = useState(puzzle);
  // index of the letter whose audio is currently being played
  // set to -1 when not playing; set to 0 to start playing
  const [letterBeingPlayed, setLetterBeingPlayed] = useState(-1);
  const [currentWord, setCurrentWord] = useState(0); // index

  useEffect(() => {
    // onInit
    setInProgressPuzzle(puzzle);
  }, [puzzle]);

  // play audio file of a letter, recursive
  useEffect(() => {
    const word = puzzle.words[currentWord].spanishWord;

    if (letterBeingPlayed < 0) return;
    if (letterBeingPlayed >= word.length) {
      setLetterBeingPlayed(-1);
      return;
    }

    const letterAudio = new Audio(
      `/alphabet-audio/${word[letterBeingPlayed]}.mp3`,
    );

    letterAudio.onended = () => {
      delay(
        () => setLetterBeingPlayed(letterBeingPlayed + 1),
        DELAY_BETWEEN_LETTERS,
      );
    };

    letterAudio.play().catch((error) => console.error("audio failed", error));

    return () => {
      letterAudio.pause();
      letterAudio.onended = null; // remove event listener
    };
  }, [letterBeingPlayed]);

  // play letters of a word, in sequence
  const playWord = (wordIndex: number) => {
    setCurrentWord(wordIndex);
    setLetterBeingPlayed(0);
  };

  return (
    <div className="ortografia-game">
      <div id="game">
        {inProgressPuzzle.words.map((word, i) => (
          <div className="word" key={word.spanishWord}>
            <button onClick={() => playWord(i)}>
              <img src="https://twemoji.maxcdn.com/v/latest/72x72/1f50a.png" />
            </button>
            {[...word.spanishWord].map(() => (
              <>_ </>
            ))}
          </div>
        ))}
      </div>
    </div>
  );
}
