import { useEffect, useRef, useState, type ChangeEvent } from "react";
import "./OrtografiaGame.scss";
import { addDateToLocalStorage } from "../utils/localstorage";
import Win from "../components/Win";
import { GameString } from "../types";
import clsx from "clsx";
import { delay } from "lodash";
import type { OrtografiaPuzzle } from "./types";
import Word from "./OrtografiaWord";

const DELAY_BETWEEN_LETTERS = 0; // ms

interface OrtografiaGameProps {
  todayString: string;
  puzzle: OrtografiaPuzzle;
  /** if false, the puzzle was generated by the user using the UI generator */
  isDailyPuzzle: boolean;
}

export default function OrtografiaGame(props: OrtografiaGameProps) {
  const { isDailyPuzzle, puzzle, todayString } = props;

  const [hasWon, setHasWon] = useState(false);
  const [showWinScreen, setShowWinScreen] = useState(false);
  const [inProgressPuzzle, setInProgressPuzzle] = useState(puzzle);
  // index of the letter whose audio is currently being played
  // set to -1 when not playing; set to 0 to start playing
  const [letterBeingPlayed, setLetterBeingPlayed] = useState(-1);
  const [currentWord, setCurrentWord] = useState(0); // index
  const [input, setInput] = useState("");
  const inputRef = useRef<HTMLInputElement>(null);

  const isAudioPlaying = letterBeingPlayed > -1;

  const win = () => {
    if (inputRef.current) inputRef.current.disabled = true;
    setHasWon(true);
    setShowWinScreen(true);

    if (isDailyPuzzle) {
      addDateToLocalStorage(GameString.Ortografia, todayString);
    }
  };

  useEffect(() => {
    // onInit
    setInProgressPuzzle(puzzle);

    setHasWon(false);
    setShowWinScreen(false);
  }, [puzzle]);

  // check for win condition
  useEffect(() => {
    if (!inProgressPuzzle.find((word) => !word.isCorrect)) {
      win();
    }
  }, [inProgressPuzzle]);

  const closeWinScreen = () => {
    setShowWinScreen(false);
  };

  // play audio file of a letter, recursive
  useEffect(() => {
    if (currentWord > inProgressPuzzle.length - 1) return;

    const word = inProgressPuzzle[currentWord].spanishWord;

    if (letterBeingPlayed < 0) return;
    if (letterBeingPlayed >= word.length) {
      setLetterBeingPlayed(-1);
      return;
    }

    const letterAudio = new Audio(
      `/alphabet-audio/${word[letterBeingPlayed]}.mp3`,
    );

    letterAudio.onended = () => {
      delay(
        () => setLetterBeingPlayed(letterBeingPlayed + 1),
        DELAY_BETWEEN_LETTERS,
      );
    };

    letterAudio.play().catch((error) => console.error("audio failed", error));

    return () => {
      letterAudio.pause();
      letterAudio.onended = null; // remove event listener
    };
  }, [letterBeingPlayed]);

  // play letters of a word, in sequence
  const playWord = (wordIndex: number, pause?: number) => {
    // if the word is currently playing, clicking the play button should instead pause it
    if (wordIndex === currentWord && letterBeingPlayed > -1) {
      setLetterBeingPlayed(-1);
      return;
    }

    // focus the input if it isn't already
    inputRef.current?.focus();
    setCurrentWord(wordIndex);

    if (pause) {
      setTimeout(() => setLetterBeingPlayed(0), pause);
    } else {
      setLetterBeingPlayed(0);
    }
  };

  const handleInputChange = (e: ChangeEvent<HTMLInputElement>) => {
    setInput(e.target.value);

    if (
      e.target.value.toLowerCase() ===
      inProgressPuzzle[currentWord].spanishWord.toLowerCase()
    ) {
      // move on to next word
      inProgressPuzzle[currentWord].isCorrect = true;
      setInput("");
      playWord(currentWord + 1, 300);
    }
  };

  return (
    <div className={clsx("ortografia-game", hasWon && "game-over")}>
      {showWinScreen && <Win closeWinScreen={closeWinScreen} canBeHidden />}
      <div id="game">
        <div className="controls">
          <button className="play-pause" onClick={() => playWord(currentWord)}>
            {isAudioPlaying ? (
              <img src="https://Card.maxcdn.com/v/latest/72x72/23f9.png" />
            ) : (
              <img src="https://Card.maxcdn.com/v/latest/72x72/25b6.png" />
            )}
          </button>
          <input
            id="input"
            type="text"
            ref={inputRef}
            value={input}
            onChange={handleInputChange}
            lang="es"
            maxLength={inProgressPuzzle[currentWord]?.spanishWord.length || 0}
          />
        </div>
        {inProgressPuzzle.map((word, i) => (
          <Word
            key={word.spanishWord}
            word={word}
            wordIndex={i}
            activeIndex={currentWord}
            currentInput={input}
          />
        ))}
      </div>
    </div>
  );
}
