import { useEffect, useRef, useState } from "react";
import "./OrtografiaMatchingGame.scss";
import "animate.css";
import { addDateToLocalStorage } from "../utils/localstorage";
import { GameString } from "../types";
import clsx from "clsx";
import type { OrtographiaPair, OrtografiaPuzzle } from "./types";
import Srand from "seeded-rand";
import { useCable } from "../utils/useCable";

interface OrtografiaMatchingGameProps {
  todayString: string;
  puzzle: OrtografiaPuzzle;
  /** if false, the puzzle was generated by the user using the UI generator */
  isDailyPuzzle: boolean;
  onWin: () => void;
}

const computedStyle = window.getComputedStyle(
  document.getElementById("root") || document.documentElement,
);
const CABLE_COLORS = [
  computedStyle.getPropertyValue("--blue-400"),
  computedStyle.getPropertyValue("--purple-400"),
  computedStyle.getPropertyValue("--yellow-light"),
  computedStyle.getPropertyValue("--orange-400"),
  computedStyle.getPropertyValue("--green-400"),
];

export default function OrtografiaMatchingGame(
  props: OrtografiaMatchingGameProps,
) {
  const { isDailyPuzzle, onWin, puzzle, todayString } = props;

  const gameRef = useRef<HTMLDivElement>(null);
  const [hasWon, setHasWon] = useState(false);
  const [inProgressPuzzle, setInProgressPuzzle] = useState(puzzle);
  const [definitions, setDefinitions] = useState<string[]>([]);
  const [inProgressMatchSpanish, setInProgressMatchSpanish] =
    useState<string>();
  const [inProgressMatchEnglish, setInProgressMatchEnglish] =
    useState<string>();
  const [matchedPairs, setMatchedPairs] = useState<OrtographiaPair[]>([]);

  const { svgRef, endCable, removeCable, startCable } = useCable(CABLE_COLORS);

  const win = () => {
    setHasWon(true);
    onWin();

    if (isDailyPuzzle) {
      addDateToLocalStorage(GameString.Ortografia, todayString);
    }
  };

  const shuffleDefinitions = () => {
    // use seeded shuffling so this date's puzzle is always in this order
    Srand.seed(Date.parse(todayString));
    const shuffled = Srand.sample(puzzle, inProgressPuzzle.length);
    const definitions = shuffled.map((word) => word.definition);
    setDefinitions(definitions);
  };

  useEffect(() => {
    // onInit
    shuffleDefinitions();

    setInProgressPuzzle(puzzle);

    setHasWon(false);
  }, [puzzle]);

  // check for win condition
  useEffect(() => {
    if (!inProgressPuzzle.find((word) => !word.isCorrect)) {
      win();
    } else if (matchedPairs.length === inProgressPuzzle.length) {
      // if all words are connected, drop incorrect connections
      // do it backwards so indices are correct
      for (let i = inProgressPuzzle.length - 1; i >= 0; i--) {
        const word = inProgressPuzzle[i];
        if (!word.isCorrect) {
          // remove from matchedPairs
          removePairFromArray(word.spanishWord);
        }
      }
    }
  }, [inProgressPuzzle, matchedPairs]);

  const addPairToArray = (spanish: string, english: string) => {
    setMatchedPairs((prevItems) => [
      ...prevItems,
      {
        spanish,
        english,
      },
    ]);
    setInProgressMatchSpanish(undefined);
    setInProgressMatchEnglish(undefined);
    checkIfCorrectAndSet(spanish, english);
  };

  const removePairFromArray = (spanish?: string, english?: string) => {
    if (spanish) {
      // remove cables
      const pairIndex = matchedPairs.findIndex(
        (pair) => pair.spanish === spanish,
      );
      if (pairIndex !== -1) removeCable(pairIndex);

      setMatchedPairs((prevItems) =>
        prevItems.filter((item) => item.spanish !== spanish),
      );

      setCorrect(false, spanish);
    }
    if (english) {
      const pairIndex = matchedPairs.findIndex(
        (pair) => pair.english === english,
      );
      if (pairIndex !== -1) removeCable(pairIndex);

      setMatchedPairs((prevItems) =>
        prevItems.filter((item) => item.english !== english),
      );

      setCorrect(false, undefined, english);
    }
  };

  const checkIfCorrectAndSet = (spanish: string, english: string) => {
    const word = inProgressPuzzle.find((w) => w.spanishWord === spanish);

    if (word?.definition === english) {
      setCorrect(true, spanish, english);
    }
  };

  const setCorrect = (
    isCorrect: boolean,
    spanish?: string,
    english?: string,
  ) => {
    setInProgressPuzzle((prevPuzzle) => {
      return prevPuzzle.map((word) => {
        if (spanish) {
          return word.spanishWord === spanish ? { ...word, isCorrect } : word;
        }
        if (english) {
          return word.definition === english ? { ...word, isCorrect } : word;
        }
        return word;
      });
    });
  };

  const onClickSpanish = (
    e: React.MouseEvent<HTMLButtonElement>,
    word: string,
  ) => {
    if (hasWon) return;

    // if the word clicked is already in `matchedPairs`, remove pair and start fresh
    const isPaired = matchedPairs.map((pair) => pair.spanish).includes(word);
    if (isPaired) {
      removePairFromArray(word);
    }

    // if the word clicked is the active one, make it unactive
    if (inProgressMatchSpanish === word) {
      setInProgressMatchSpanish(undefined);

      // remove in-progress cable
      removeCable();
      return;
    } else {
      setInProgressMatchSpanish(word);

      if (!inProgressMatchEnglish) {
        if (gameRef.current) {
          const gameBBox = gameRef.current.getBoundingClientRect();
          startCable(
            e.currentTarget,
            "right",
            gameBBox.left + gameBBox.width / 2,
            gameBBox.bottom - 8,
          );
        }
      }
    }

    if (inProgressMatchEnglish) {
      // add to array
      addPairToArray(word, inProgressMatchEnglish);
      endCable(e.currentTarget, "right");
    }
  };

  const onClickEnglish = (
    e: React.MouseEvent<HTMLButtonElement>,
    word: string,
  ) => {
    if (hasWon) return;

    // if the word clicked is already in `matchedPairs`, remove pair and start fresh
    const isPaired = matchedPairs.map((pair) => pair.english).includes(word);
    if (isPaired) {
      removePairFromArray(undefined, word);
    }

    // if the word clicked is the active one, make it unactive
    if (inProgressMatchEnglish === word) {
      setInProgressMatchEnglish(undefined);

      // remove in-progress cable
      removeCable();
      return;
    } else {
      setInProgressMatchEnglish(word);

      if (!inProgressMatchSpanish) {
        if (gameRef.current) {
          const gameBBox = gameRef.current.getBoundingClientRect();
          startCable(
            e.currentTarget,
            "left",
            gameBBox.left + gameBBox.width / 2,
            gameBBox.bottom - 8,
          );
        }
      }
    }

    if (inProgressMatchSpanish) {
      // add to array
      addPairToArray(inProgressMatchSpanish, word);
      endCable(e.currentTarget, "left");
    }
  };

  return (
    <div
      className={clsx("ortografia-matching-game", hasWon && "game-over")}
      ref={gameRef}
    >
      <div id="game">
        <div className="spanish-column">
          {inProgressPuzzle.map((word) => {
            const isPaired = matchedPairs
              .map((pair) => pair.spanish)
              .includes(word.spanishWord);
            const isActive = inProgressMatchSpanish === word.spanishWord;

            return (
              <button
                onClick={(e) => onClickSpanish(e, word.spanishWord)}
                className={clsx(
                  "card animate__animated",
                  isActive && "active",
                  isPaired ? "animate__pulse paired" : "animate__headShake",
                )}
                disabled={hasWon}
                key={word.spanishWord}
              >
                {word.spanishWord}
              </button>
            );
          })}
        </div>
        <div className="spacer" />
        <div className="english-column">
          {definitions.map((definition) => {
            const isPaired = matchedPairs
              .map((pair) => pair.english)
              .includes(definition);
            const isActive = inProgressMatchSpanish === definition;

            return (
              <button
                onClick={(e) => onClickEnglish(e, definition)}
                className={clsx(
                  "card animate__animated",
                  isActive && "active",
                  isPaired ? "animate__pulse paired" : "animate__headShake",
                )}
                disabled={hasWon}
                key={definition}
              >
                {definition}
              </button>
            );
          })}
        </div>
      </div>
      <svg id="cables" ref={svgRef} />
    </div>
  );
}
