import { useEffect, useRef, useState, type ChangeEvent } from "react";
import "./OrtografiaSpellingGame.scss";
import { delay } from "lodash";
import type { OrtografiaPuzzle } from "./types";
import Word from "./OrtografiaWord";

const DELAY_BETWEEN_LETTERS = 0; // ms

interface OrtografiaSpellingGameProps {
  puzzle: OrtografiaPuzzle;
  /** if false, the puzzle was generated by the user using the UI generator */
  onCompleteSpellingStage: () => void;
}

export default function OrtografiaSpellingGame(
  props: OrtografiaSpellingGameProps,
) {
  const { onCompleteSpellingStage, puzzle } = props;

  const [audioHasPlayed, setAudioPlayed] = useState(false);
  const [inProgressPuzzle, setInProgressPuzzle] = useState(puzzle);
  // index of the letter whose audio is currently being played
  // set to -1 when not playing; set to 0 to start playing
  const [letterBeingPlayed, setLetterBeingPlayed] = useState(-1);
  const [currentWord, setCurrentWord] = useState(0); // index
  const [input, setInput] = useState("");
  const inputRef = useRef<HTMLInputElement>(null);

  const isAudioPlaying = letterBeingPlayed > -1;

  const win = () => {
    // instead of showing win screen, advance to next phase of game
    if (inputRef.current) inputRef.current.disabled = true;
    onCompleteSpellingStage();
  };

  useEffect(() => {
    // onInit
    setInProgressPuzzle(puzzle);
  }, [puzzle]);

  // check for win condition
  useEffect(() => {
    if (!inProgressPuzzle.find((word) => !word.isCorrect)) {
      win();
    }
  }, [inProgressPuzzle]);

  // play audio file of a letter, recursive
  useEffect(() => {
    if (currentWord > inProgressPuzzle.length - 1) return;

    const word = inProgressPuzzle[currentWord].spanishWord;

    if (letterBeingPlayed < 0) return;
    if (letterBeingPlayed >= word.length) {
      setLetterBeingPlayed(-1);
      return;
    }

    const letterAudio = new Audio(
      `/alphabet-audio/${word[letterBeingPlayed]}.mp3`,
    );

    letterAudio.onended = () => {
      delay(
        () => setLetterBeingPlayed(letterBeingPlayed + 1),
        DELAY_BETWEEN_LETTERS,
      );
    };

    letterAudio
      .play()
      .then(() => setAudioPlayed(true))
      .catch((error) => console.error("audio failed", error));

    return () => {
      letterAudio.pause();
      letterAudio.onended = null; // remove event listener
    };
  }, [letterBeingPlayed]);

  // play letters of a word, in sequence
  const playWord = (wordIndex: number, pause?: number) => {
    // if the word is currently playing, clicking the play button should instead pause it
    if (wordIndex === currentWord && letterBeingPlayed > -1) {
      setLetterBeingPlayed(-1);
      return;
    }

    // focus the input if it isn't already
    inputRef.current?.focus();
    setCurrentWord(wordIndex);

    if (pause) {
      setTimeout(() => setLetterBeingPlayed(0), pause);
    } else {
      setLetterBeingPlayed(0);
    }
  };

  const handleInputChange = (e: ChangeEvent<HTMLInputElement>) => {
    setInput(e.target.value);

    if (
      e.target.value.toLowerCase() ===
      inProgressPuzzle[currentWord].spanishWord.toLowerCase()
    ) {
      // move on to next word
      setInProgressPuzzle((prevPuzzle) => {
        return prevPuzzle.map((word, i) => {
          return i === currentWord ? { ...word, isCorrect: true } : word;
        });
      });
      setInput("");
      playWord(currentWord + 1, 300);
    }
  };

  const handleFocus = () => {
    // the first time the input field is focused, the audio should start playing
    if (letterBeingPlayed < 0 && !audioHasPlayed) {
      playWord(currentWord, 300);
    }
  };

  return (
    <div className="ortografia-spelling-game">
      <div id="game">
        <div className="controls">
          <button className="play-pause" onClick={() => playWord(currentWord)}>
            {isAudioPlaying ? (
              <img src="https://Card.maxcdn.com/v/latest/72x72/23f9.png" />
            ) : (
              <img src="https://Card.maxcdn.com/v/latest/72x72/25b6.png" />
            )}
          </button>
          <input
            id="input"
            type="text"
            ref={inputRef}
            value={input}
            onChange={handleInputChange}
            onFocus={handleFocus}
            lang="es"
            maxLength={inProgressPuzzle[currentWord]?.spanishWord.length || 0}
          />
        </div>
        {inProgressPuzzle.map((word, i) => (
          <Word
            key={word.spanishWord}
            word={word}
            wordIndex={i}
            activeIndex={currentWord}
            currentInput={input}
          />
        ))}
      </div>
    </div>
  );
}
